# -*- coding: utf-8 -*-
"""transaction categorezation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-mTmtcIwnWN044zzPc_lxSxviImYnUi
"""

# Installer la lib
!pip install datasets

# Charger directement sans télécharger
from datasets import load_dataset

ds = load_dataset("DoDataThings/us-bank-transaction-categories")
df = ds['train'].to_pandas()

print(df.head())
print(df.columns)
print(df.shape)

from sklearn.model_selection import train_test_split

X = df['description']
y = df['category']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(f"Données d'entrainement : {len(X_train)}")
print(f"Données de test : {len(X_test)}")

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', MultinomialNB())
])

model.fit(X_train, y_train)

print("✅ Modèle entraîné avec succès !")

from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"=== ACCURACY : {accuracy*100:.2f}% ===")
print("\n=== RAPPORT DÉTAILLÉ ===")
print(classification_report(y_test, y_pred))

# Monte Google Drive (1 clic)
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df_perso = pd.read_csv('/content/drive/MyDrive/bouchra_transactions.csv')

print(f"✅ {len(df_perso)} transactions chargées !")
print(df_perso.head())

# Test avec le modèle
mes_transactions = df_perso['description'].tolist()
predictions = model.predict(mes_transactions)

# Ajoute les prédictions
df_perso['predicted_category'] = predictions

# Affiche les résultats
print("\n=== RÉSULTATS ===")
print(df_perso[['description', 'category', 'predicted_category']].head(20))

# Sauvegarde le fichier avec les prédictions
df_perso.to_csv('resultats_model1.csv', index=False)

from google.colab import files
files.download('resultats_model1.csv')

print("✅ Résultats sauvegardés !")